Hiadmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('navi/', include('navigation.urls')),
    path('ops/', include('operations.urls')),
    path('daily/', include('dailyreport.urls')),
    path('sys/', include('system.urls')),
]

operations/urls.py
from django.urls import path, re_path
from operations import views

app_name = 'ops'
urlpatterns = [
    path('service/', views.MyOpsView.as_view(), name='service'),
    re_path('service/(\d+)/', views.OpsDetailView.as_view(), name='service_more'),
    re_path('hosts/(\d+)/', views.MyHostsView.as_view(), name='hosts_id')
]

system/urls.py
from django.urls import path, include
from django.urls import re_path
from system import views_user, views_structure, views
from django.views.static import serve
from Hiadmin.settings import MEDIA_ROOT

app_name = 'sys'
urlpatterns = [
    path('login/', views_user.LoginView.as_view(), name='login'),
    path('logout/', views_user.LogoutView.as_view(), name='logout'),
    re_path(r'media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('structure/', views_structure.StructureView.as_view(), name='structure'),
    path('structure/create/', views_structure.StructureCreateView.as_view(), name='structure_create'),
    path('structure/list/', views_structure.StructureListView.as_view(), name='structure_list'),
    path('structure/add_user/', views_structure.Structure2UserView.as_view(), name='structure_add_user'),

    path('user/', views_user.UserView.as_view(), name='user'),
    path('user/list/', views_user.UserListView.as_view(), name='user_list'),
    path('user/create/', views_user.UserCreateView.as_view(), name='user_create'),
    path('user/detail/', views_user.UserDetailView.as_view(), name='user_detail'),
    path('user/update/', views_user.UserUpdateView.as_view(), name='user_update'),
    path('user/delete/', views_user.UserDeleteView.as_view(), name='user_delete'),
    path('user/enable/', views_user.UserEnableView.as_view(), name='user_enable'),
    path('user/disable/', views_user.UserDisableView.as_view(), name='user_disable'),
    path('user/password_change/', views_user.PasswordChangeView.as_view(), name='password_change'),

]

operations/models.py
from django.db import models

# Create your models here.

OPS_STATUS = (
    (str(1), u"使用中"),
    (str(2), u"未使用"),
    (str(3), u"故障"),
    (str(4), u"其它"),
)

OPS_LEVER = (
    (str(1), u"1"),
    (str(2), u"2"),
)

DEPARTMENT = (
    ("yyglb", "运营管理部"),
    ("hlwjrb", "互联网金融部"),
    ("xxkfb", "信息开发部"),
    ("ersyb", "E融事业部"),
    ("yhkb", "银行卡部"),
    ("gjyw", "国际业务部"),
)

class OpsServer(models.Model):
    name = models.CharField("系统名称(简)", max_length=20)
    full_name = models.CharField("系统名称(全)", max_length=20)
    number = models.CharField("系统编号",max_length=10)
    lever = models.CharField("系统层级",choices=(('1','1'),('2','2')),max_length=20)
    en_name = models.CharField("英文缩写", max_length=20,null=True)
    platform = models.CharField("所属平台", max_length=20,null=True)
    old_lever = models.CharField("系统级别(旧)",max_length=20,null=True)
    new_lever = models.CharField("重要级别",max_length=20,null=True)
    department = models.CharField("所属部门",choices=DEPARTMENT,max_length=20,null=True)
    status = models.CharField("系统状态", choices=OPS_STATUS, max_length=20)
    ha_ip = models.GenericIPAddressField("HA地址", max_length=50,null=True)
    manager = models.CharField("运营负责人", max_length=50, null=True)
    dev_manager = models.CharField("开发负责人", max_length=50, null=True)
    sale_manager = models.CharField("业务负责人", max_length=50, null=True)
    vendor = models.CharField("开发商", max_length=50, null=True)
    vendor_person = models.CharField("开发商联系人", max_length=50, null=True)
    vendor_phone = models.CharField("开发商联系电话", max_length=50, null=True)
    online_time = models.DateTimeField("投产时间",null=True,blank=True)
    create_time = models.DateTimeField("创建时间", auto_now_add=True, null=True)
    mobity_time = models.DateTimeField("修改时间", auto_now=True, null=True)
    def __str__(self):
        return self.name

class OpsHost(models.Model):
    hostname = models.CharField("主机名", max_length=50, null=True, blank=True)
    ip = models.GenericIPAddressField("主机IP", max_length=15)
    system = models.CharField("主机系统", max_length=50, null=True, blank=True)
    manager = models.CharField("主机管理人员", max_length=50, null=True)
    use_port1 = models.CharField("使用的端口", max_length=50, null=True)
    use_port2 = models.CharField("使用的端口", max_length=50, null=True)
    use_port3 = models.CharField("使用的端口", max_length=50, null=True)
    use_port4 = models.CharField("使用的端口", max_length=50, null=True)
    status = models.CharField("使用状态", choices=OPS_STATUS ,max_length=20, null=True, blank=True)
    ops_server = models.ForeignKey('OpsServer', on_delete=models.CASCADE)
    create_time = models.DateTimeField("创建时间", auto_now_add=True, null=True)
    mobity_time = models.DateTimeField("修改时间", auto_now=True, null=True)

    def __str__(self):
        return self.hostname

operations/views.py
from django.shortcuts import render, render_to_response
from .models import *
from django.views import View
from system.mixin import LoginRequiredMixin


class MyOpsView(LoginRequiredMixin, View):

    def get(self, request):
        title = "Ops"
        username = "Hi"
        ops_servers = OpsServer.objects.all()

        return render_to_response("operations/service_list.html", locals())


class OpsDetailView(LoginRequiredMixin, View):

    def get(self, request):
        title = "Ops"
        username = "Hi"
        ops_servers = OpsServer.objects.filter(id=id)

        return render_to_response("operations/service_more.html", locals())


class MyHostsView(LoginRequiredMixin, View):

    def get(self, request):
        title = "Ops"
        username = "Hi"
        ops_hosts = OpsHost.objects.filter(ops_server_id=id)

        return render_to_response("operations/hosts.html", locals())

templates/operations/add.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}



<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="content  wrapper site-min-height">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h4 class="mb"><i class="fa fa-angle-right"></i> 添加系统条目</h4>

            </div>

            <div class="box-body">
                <form action="{% url 'ops_add' %}" method="post">
                    {% csrf_token %}
                    {{ ops_form.as_p }}
                    <input type="submit" class="btn btn-clear-g" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'ops' %}">
                        <li style="width: 60pt" class="btn btn-clear-g" value="">返回</li>
                    </a><br>
                </form>
            </div>
            <h4>{{ tips }}</h4>
            <!-- /.box-body -->
            <div class="box-footer">
                <br>
                <i class="fa fa-info-circle"></i> 请勿重复添加条目
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
{% endblock %}
<!--main content end-->

templates/operations/hosts.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="wrapper site-min-height">

        <div class="row mt">
            <div class="col-md-12">
                <div class="content-panel">
                    <table class="table table-striped table-advance table-hover">
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                                    title="Remove">
                                <i class="fa fa-times"></i></button>
                        </div>
                        <h4><i class="fa fa-angle-right"></i> Hosts Table</h4>
                        <hr>
                        <thead>
                        <tr>
                            <th><i class=" fa fa-edit"></i>HostName</th>
                            <th class="hidden-phone"><i class="fa fa-question-circle"></i>IP</th>
                            <th><i class="fa fa-bookmark"></i>System</th>
                            <th><i class=" fa fa-edit"></i>Admin</th>
                            <th><i class=" fa fa-edit"></i>Status</th>
                            <th><i class=" fa fa-edit"></i>Setting</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in ops_hosts %}
                            <tr>
                                <td class="hidden-phone">{{ s.hostname }}</td>
                                <td class="hidden-phone">{{ s.ip }}</td>
                                <td class="hidden-phone">{{ s.system }}</td>
                                <td class="hidden-phone">{{ s.manager }}</td>
                                <td><span class="label label-info label-mini">{{ s.get_status_display }}</span></td>
                                <td>
                                    <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                    <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                    <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /content-panel -->
            </div>
            <!-- /col-md-12 -->
        </div>

    </section>
{% endblock %}
<!--main content end-->

templates/operations/service_list.html
{% extends "base.html" %}

{% block title %}{{ title|default:"Ops" }}{% endblock %}


<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="wrapper site-min-height">

        <div class="row mt">
            <div class="col-md-12">
                <div class="content-panel">
                    <table class="table table-striped table-advance table-hover">
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                                    title="Remove">
                                <i class="fa fa-times"></i></button>
                        </div>
                        <h4><i class="fa fa-angle-right"></i>Service Table</h4>
                        <hr>
                        <thead>
                        <tr>
                            <th><i class="fa fa-bullhorn"></i>系统名称</th>
                            <th><i class=" fa fa-edit"></i>级别</th>
                            <th><i class=" fa fa-edit"></i>所属部门</th>
                            <th><i class=" fa fa-edit"></i>运营负责人</th>
                            <th class="hidden-phone"><i class="fa fa-question-circle"></i> 开发负责人</th>
                            <th><i class=" fa fa-edit"></i>主机信息</th>
                            <th><i class=" fa fa-edit"></i>状态</th>
                            <th></th>
                        </tr>
                        </thead>
                        {% for s in ops_servers %}
                            <tbody>
                            <tr>
                                <td><a>{{ s.name }}</a></td>
                                <td class="hidden-phone">{{ s.lever }}</td>
                                <td class="hidden-phone">{{ s.get_department_display }}</td>
                                <td class="hidden-phone">{{ s.manager }}</td>

                                <td class="hidden-phone">{{ s.manager }}</td>
                                <td><a href="{% url "ops:hosts_id" s.id %}">{{ s.ha_ip }}</a></td>
                                <td><span class="label label-info label-mini">{{ s.get_status_display }}</span></td>
                                <td>
                                    <a href="{% url "ops:service_more" s.id %}">查看更多</a>
                                    {#                                    <button href="{% url "ops:service_more" s.id %}" class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>#}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /content-panel -->
            </div>
            <!-- /col-md-12 -->
        </div>

    </section>
{% endblock %}
<!--main content end-->

templates/operations/service_more.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block aside %}
        <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <p class="centered"><a href="/navi/"><img src="/static/img/ny.jpg" class="img-circle" width="100"></a>
                </p>
                <h5 class="centered">{{ username }},welcome</h5>


                <li class="sub-menu">
                    <a class="active" href="{% url "ops:service" %}">
                        <i class="fa fa-desktop"></i>
                        <span>Operations</span>
                    </a>
{#                    <ul class="sub">#}
{#                        <li><a href="/ops/index">Service List</a></li>#}
{#                        <li><a href="/ops/add">Service Add</a></li>#}
{#                        <li><a href="/ops/hosts">Host List</a></li>#}
{#                        <li><a href="/ops/hosts_add">Host Add</a></li>#}
{#                    </ul>#}
                </li>

            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
{% endblock %}
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="wrapper site-min-height">
 {% for host in ops_servers %}
        <div class="row mt">
            <div class="box">
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="product_project_table">
                      <thead>
                        <tr>
                            <th>项目</th>
                            <th>数值</th>
                        </tr>
                      </thead>
                            <tbody>
                                <tr  class="text-danger">
                                    <td>系统名称(简)</td>
                                    <td>{{ host.name }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>系统层级</td>
                                    <td>{{ host.lever }}</td>
                                </tr>
                                 <tr class="even gradeX">
                                    <td>系统编号</td>
                                    <td>{{ host.number }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>系统全称</td>
                                    <td>{{ host.full_name }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>英文缩写</td>
                                    <td>{{ host.en_name }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>所属平台</td>
                                    <td>{{ host.platform }}</td>
                                </tr>
                                <tr class="even gradeX">
                                <td>级别(旧)</td>
                                <td>
                                    {{ host.old_lever }}
                                </td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>所属部门</td>
                                    <td>{{ host.get_department_display }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>重要级别</td>
                                    <td>{{ host.new_lever }}</td>
                                </tr>
                                <tr class="text-danger">
                                    <td>使用状态</td>
                                    <td>{{ host.get_status_display }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>开发负责人</td>
                                    <td>{{ host.dev_manager }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>运营负责人</td>
                                    <td>{{ host.manager }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>业务负责人</td>
                                    <td>{{ host.sale_manager }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>开发商</td>
                                    <td>{{ host.vendor }}</td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>开发商联系人</td>
                                    <td>{{ host.vendor_person }}</td>
                                </tr>
                             <tr class="even gradeX">
                                    <td>开发商电话</td>
                                    <td>{{ host.vendor_phone }}</td>
                                </tr>
                            </tbody>
                  </table>
                </div>
        </div>
            <!-- /col-md-12 -->
        </div>
{% endfor %}
    </section>
{% endblock %}
<!--main content end-->