Hiadmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('navi/', include('navigation.urls')),
    path('ops/', include('operations.urls')),
    path('daily/', include('dailyreport.urls')),
    path('sys/', include('system.urls')),
]

dailyreport/urls.py
from django.urls import path
from dailyreport import views

app_name = 'daily'
urlpatterns = [
    path('', views.DailyReportView.as_view(), name='report'),
    path('myreport', views.MyReportView.as_view(), name='myreport'),
    path('create/', views.ReportCreateView.as_view(), name='report_create'),
    path('detail/', views.ReportDetailView.as_view(), name='report_detail')
]

system/urls.py
from django.urls import path, include
from django.urls import re_path
from system import views_user, views_structure, views
from django.views.static import serve
from Hiadmin.settings import MEDIA_ROOT

app_name = 'sys'
urlpatterns = [
    path('login/', views_user.LoginView.as_view(), name='login'),
    path('logout/', views_user.LogoutView.as_view(), name='logout'),
    re_path(r'media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('structure/', views_structure.StructureView.as_view(), name='structure'),
    path('structure/create/', views_structure.StructureCreateView.as_view(), name='structure_create'),
    path('structure/list/', views_structure.StructureListView.as_view(), name='structure_list'),
    path('structure/add_user/', views_structure.Structure2UserView.as_view(), name='structure_add_user'),

    path('user/', views_user.UserView.as_view(), name='user'),
    path('user/list/', views_user.UserListView.as_view(), name='user_list'),
    path('user/create/', views_user.UserCreateView.as_view(), name='user_create'),
    path('user/detail/', views_user.UserDetailView.as_view(), name='user_detail'),
    path('user/update/', views_user.UserUpdateView.as_view(), name='user_update'),
    path('user/delete/', views_user.UserDeleteView.as_view(), name='user_delete'),
    path('user/enable/', views_user.UserEnableView.as_view(), name='user_enable'),
    path('user/disable/', views_user.UserDisableView.as_view(), name='user_disable'),
    path('user/password_change/', views_user.PasswordChangeView.as_view(), name='password_change'),

]

dailyreport/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your models here.
class DailyReport(models.Model):
    CAT_CHOICE = (
        ('0', '工作日报'),
        ('1', '项目报告'),
        ('2', '投产报告'),
        ('3', '其他任务')
    )
    category = models.CharField(max_length=20, choices=CAT_CHOICE, default='0')
    content = models.TextField(verbose_name='工作日报')
    user = models.ForeignKey(User, related_name='report_user', on_delete=models.DO_NOTHING, default='')
    attention = models.ManyToManyField(User, related_name='attention', blank=True)
    start_time = models.DateTimeField(default='', verbose_name='开始时间')
    end_time = models.DateTimeField(default='', verbose_name='结束时间')
    add_time = models.DateField(auto_now_add=True, verbose_name="添加时间")

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = '工作日报'
        verbose_name_plural = verbose_name

dailyreport/forms.py
from django import forms
from .models import DailyReport


class DailyReportForm(forms.ModelForm):
    class Meta:
        model = DailyReport
        fields = '__all__'

dailyreport/views.py
import json
import re
from datetime import datetime, timedelta
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.http import HttpResponse
from django.contrib.auth import get_user_model

from system.mixin import LoginRequiredMixin
from .models import DailyReport
from .forms import DailyReportForm

User = get_user_model()


class MyReportView(View):
    """
    大家都可以查看，不需要权限
    """
    def get(self, request):
        ret = dict()
        my_report_all = DailyReport.objects.all()
        ret['my_report_all'] = my_report_all
        return render(request, 'dailyreport/myreport.html', ret)

class DailyReportView(LoginRequiredMixin, View):
    """
    事件首页
    """
    def get(self, request):
        ret = dict()
        my_report_all = DailyReport.objects.filter(attention=int(request.user.id))
        ret['my_report_all'] = my_report_all
        return render(request, 'dailyreport/report.html', ret)


class ReportCreateView(LoginRequiredMixin, View):
    """
    事件添加
    """
    def get(self, request):
        ret = dict()
        category_all = [{'key': i[0], 'value': i[1]} for i in DailyReport.CAT_CHOICE]
        user_all = User.objects.exclude(username__in=['admin'])
        ret['category_all'] = category_all
        ret['user_all'] = user_all

        if 'calDate' in request.GET and request.GET['calDate']:
            calDate = re.split('[-: ]', request.GET['calDate'])
            Y, M, D, h, m = map(int, calDate)
            start_time = datetime(Y, M, D, h, m)
            end_time = start_time + timedelta(hours=1)
            ret['start_time'] = start_time
            ret['end_time'] = end_time

        return render(request, 'dailyreport/report_create.html', ret)

    def post(self, request):
        res = dict(result=False)
        daily_report_form = DailyReportForm(request.POST)
        if daily_report_form.is_valid():
            daily_report_form.save()
            res['result'] = True
        return HttpResponse(json.dumps(res), content_type='application/json')


class ReportDetailView( View):
    """
    日报详情：用于日历展示日报详情和修改日报内容
    """

    def get(self, request):
        ret = dict()
        if 'id' in request.GET and request.GET['id']:
            category_all = [{'key': i[0], 'value': i[1]} for i in DailyReport.CAT_CHOICE]
            report = get_object_or_404(DailyReport, pk=int(request.GET['id']))
            user_all = User.objects.exclude(id=report.user_id)
            ret['category_all'] = category_all
            ret['user_all'] = user_all
            ret['report'] = report
        return render(request, 'dailyreport/report_detail.html', ret)

    def post(self, request):
        res = dict(result=False)
        if 'id' in request.POST and request.POST['id']:
            daily_report = get_object_or_404(DailyReport, pk=int(request.POST['id']))
            daily_report_form = DailyReportForm(request.POST, instance=daily_report)
            if daily_report_form.is_valid():
                daily_report_form.save()
                res['result'] = True
        return HttpResponse(json.dumps(res), content_type='application/json')

templates/dailyreport/myreport.html
{% extends "base-1.html" %}
{% load staticfiles %}

{% block title %}{{ title }}{% endblock %}
{% block username %}{{ username|default:'Hi' }}{% endblock %}

{% block css %}
    <link href="{% static 'plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="wrapper site-min-height">
        <div class="row mt mb">
            <div class="box box-primary">
                <div class="box-body no-padding">
                    <!-- THE CALENDAR -->
                    <div id="calendar">
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </section>
{% endblock %}
<!--main content end-->

{% block scripts %}
    <script src="{% static 'plugins/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $('#DailyReport').addClass('active');
            $('#MyReport').addClass('active');

        });

    </script>

    <script type="text/javascript">

        $(function () {
            //初始化FullCalendar
            $('#calendar').fullCalendar({
                buttonText: {
                    today: '今天',
                    month: '月',
                    week: '周',
                    day: '日',
                },
                allDayText: "全天",
                timeFormat: 'HH:mm',
                views: {
                    month: {titleFormat: 'YYYY年MMMM月'},
                    week: {titleFormat: 'YYYY年MMMM月'},
                    day: {titleFormat: 'YYYY年MMMM月D日'},
                },
                monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                dayNames: ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                dayNamesShort: ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],

                contentHeight: 650,

                header: {
                    //日历头部左边：初始化切换按钮
                    left: 'prev,next today reportAddButton',
                    //日历头部中间：显示当前日期信息
                    center: 'title',
                    //日历头部右边：初始化视图
                    right: 'month,agendaWeek,agendaDay'
                },
                //设置是否显示周六和周日，设为false则不显示
                weekends: true,

                eventClick: function (calEvent, jsEvent, view) {
                    layer.open({
                        type: 2,
                        title: '日报详情',
                        shadeClose: false,
                        maxmin: true,
                        area: ['800px', '460px'],
                        content: "/daily/detail?id=" + calEvent.id,

                    });
                },
                events: [
                    {% for my_report in my_report_all %}
                        {
                            id: '{{ my_report.id }}',
                            title: '{{ my_report.content }}',
                            start: '{{ my_report.start_time | date:"Y-m-d H:i"}}',
                            end: '{{ my_report.end_time | date:"Y-m-d H:i"}}',
                            {% if my_report.category == '0'  %}
                                backgroundColor: '#0073b7',
                            {% elif my_report.category == '1' %}
                                backgroundColor: '#00a65a',
                            {% else %}
                                backgroundColor: '#dd4b39',
                            {% endif %}

                        },
                    {% endfor %}

                ],
            });
        });

    </script>
{% endblock %}

templates/dailyreport/report.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ title|default:"DailyReport" }}{% endblock %}

{% block css %}
    <link href="{% static 'plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
{% block mainbody %}
    <section class="wrapper site-min-height">
        <div class="row mt mb">
            <div class="box box-primary">
                <div class="box-body no-padding">
                    <!-- THE CALENDAR -->
                    <div id="calendar">
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </section>
{% endblock %}
<!--main content end-->

{% block scripts %}
    <script src="{% static 'plugins/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $('#DailyReport').addClass('active');
            $('#MyReport').addClass('active');

        });

    </script>

    <script type="text/javascript">
        function doCreate() {
            layer.open({
                type: 2,
                title: '新建日报',
                shadeClose: false,
                maxmin: true,
                area: ['800px', '460px'],
                content: "{% url 'daily:report' %}",
                end: function () {
                    window.location.reload();
                }
            });
        }

        $(function () {
            //初始化FullCalendar
            $('#calendar').fullCalendar({
                buttonText: {
                    today: '今天',
                    month: '月',
                    week: '周',
                    day: '日',
                },
                allDayText: "全天",
                timeFormat: 'HH:mm',
                views: {
                    month: {titleFormat: 'YYYY年MMMM月'},
                    week: {titleFormat: 'YYYY年MMMM月'},
                    day: {titleFormat: 'YYYY年MMMM月D日'},
                },
                monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                dayNames: ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                dayNamesShort: ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                // 新增内容：自定义按钮
                customButtons: {
                    reportAddButton: {
                        text: '添加',
                        click: function () {
                            alert('这是一个自定义按钮');
                        }
                    },
                },
                contentHeight: 650,

                header: {
                    //日历头部左边：初始化切换按钮
                    left: 'prev,next today reportAddButton',
                    //日历头部中间：显示当前日期信息
                    center: 'title',
                    //日历头部右边：初始化视图
                    right: 'month,agendaWeek,agendaDay'
                },
                //设置是否显示周六和周日，设为false则不显示
                weekends: true,
                dayClick: function (date, view) {
                    layer.open({
                        type: 2,
                        title: '新建日报',
                        shadeClose: false,
                        maxmin: true,
                        area: ['800px', '500px'],
                        content: "/daily/create?calDate=" + date.format("YYYY-MM-DD H:mm"),
                    });
                },
                eventClick: function (calEvent, jsEvent, view) {
                    layer.open({
                        type: 2,
                        title: '日报详情',
                        shadeClose: false,
                        maxmin: true,
                        area: ['800px', '460px'],
                        content: "/daily/detail?id=" + calEvent.id,

                    });
                },
                events: [
                    {% for my_report in my_report_all %}
                        {
                            id: '{{ my_report.id }}',
                            title: '{{ my_report.content }}',
                            start: '{{ my_report.start_time | date:"Y-m-d H:i"}}',
                            end: '{{ my_report.end_time | date:"Y-m-d H:i"}}',
                            {% if my_report.category == '0'  %}
                                backgroundColor: '#0073b7',
                            {% elif my_report.category == '1' %}
                                backgroundColor: '#00a65a',
                            {% else %}
                                backgroundColor: '#dd4b39',
                            {% endif %}

                        },
                    {% endfor %}

                ],
            });
        });

    </script>
{% endblock %}

templates/dailyreport/report_create.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='user' value="{{ request.user.id }}"/>
            <p class="box-body">
                <fieldset>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">日报类型</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" style="width:100%;" name="category">
                                {% for category in category_all %}
                                    <option value="{{ category.key }}">{{ category.value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <label class="col-sm-2 control-label">添加关注</label>

                        <div class="col-sm-3">
                            <select class="form-control select2" multiple="multiple" name="attention"
                                    data-placeholder="添加关注"
                                    style="width: 100%;">
                                {% for attention in user_all %}
                                    <option value="{{ attention.id }}">{{ attention.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">开始时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="start_time"
                                   value="{{ start_time | date:'Y-m-d H:i' }}" readonly/>
                        </div>
                        <label class="col-sm-2 control-label">结束时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="end_time"
                                   value="{{ end_time | date:'Y-m-d H:i' }}" readonly/>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">报告内容</label>
                        <div class="col-sm-8">
                            <textarea class="form-control" name="content" rows="5"></textarea>
                        </div>
                    </div>
            <p>
                <small class="text-danger margin-l-5">* 关注人可以查看本条报告内容</small>
            </p>
            </fieldset>

            <div class="box-footer ">

                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script type="text/javascript">

        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'daily:report_create' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('数据保存成功！', {icon: 1}, function (index) {
                            parent.location.reload();
                        });
                    } else {
                        layer.alert('数据保存失败,请将信息填写完整！', {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });

        /*input 时间输入选择*/
        $(".form_datetime").datetimepicker({
            language: 'zh',
            //minView: 'month',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //format: 'yyyy-mm-dd hh:ss'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        // select2
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        });
    </script>

{% endblock %}

templates/dailyreport/report_detail.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <div class="box-header with-border">
            <div class="user-block">
{#                <img class="img-circle" src="/media/{{ report.user.image }}" alt="User Image">#}
                <span class="username"><a href="#">{{ report.user.name }}</a></span>
                <span class="description">创建时间: {{ report.add_time }}</span>
            </div>
            <!-- /.user-block -->
            <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-toggle="tooltip" title="Mark as read">
                    <i class="fa fa-circle-o"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <p class="box-body">
            <fieldset>
                <input type="hidden" name="user" value="{{ request.user.id }}">
                <input type="hidden" name="id" value="{{ report.id }}">
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">事件类型</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" style="width:100%;" name="category">
                            <option value="{{ report.category }}">{{ report.get_category_display }}</option>
                            {% for category in category_all %}
                                <option value="{{ category.key }}">{{ category.value }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <label class="col-sm-2 control-label">事件人员</label>
                    <div class="col-sm-3">
                        <select class="form-control select2" multiple="multiple" name="attention"
                                data-placeholder="添加关注"
                                style="width: 100%;">
                            {% for attention in user_all %}
                                <option value="{{ attention.id }}" {% if attention in report.attention.all %}selected="selected" {% endif %}>{{ attention.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">开始时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="start_time"
                               readonly value="{{ report.start_time |date:'Y-m-d H:i' }}"/>
                    </div>
                    <label class="col-sm-2 control-label">结束时间</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control pull-right form_datetime" name="end_time" readonly
                               value="{{ report.end_time |date:'Y-m-d H:i' }}"/>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label">报告内容</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="content" rows="5">{{ report.content }}</textarea>
                    </div>
                </div>
            </fieldset>

            <div class="box-footer ">

                <div class="row span7 text-center ">
                    {% ifequal request.user.id  report.user_id %}
                        <button type="button" id="btnSave" class="btn btn-info margin-right ">保存修改</button>
                    {% endifequal %}
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script type="text/javascript">

        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'daily:report_detail' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('数据保存成功！', {icon: 1}, function (index) {
                            parent.location.reload();
                        });
                    } else {
                        layer.alert('数据保存失败,请将信息填写完整！', {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                    return;
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });

        /*input 时间输入选择*/
        $(".form_datetime").datetimepicker({
            language: 'zh',
            //minView: 'month',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        // select2
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        });

    </script>

{% endblock %}